# This is a Panamax mirror. It is a self-contained directory made to be easily copied
# to an offline network or machine via rsync, USB, or another method.

# While Panamax handles grabbing files from the Internet, it does not handle hosting
# on the offline. Since everything in the mirror is static, it should be
# fairly easily hosted using nginx, and git for the crates.io-index mirror.

[mirror]
# Global mirror settings.

# Number of download retries before giving up.
retries = 5

# Contact information for the user agent.
# As per crates.io crawling policy, lacking this information may cause your IP to be blocked.
# It's recommended that this be set to your email address or a website you own.
# If you're okay with this, this parameter can be removed.
contact = "yehudanahon98@gmail.com"

[rustup]
# These are the configuration parameters for the rustup half of the mirror.
# This will download the rustup-init files, as well as all components needed
# to run Rust on a machine.

# Perform rustup synchronization. Set this to false if you only want to mirror crates.io.
sync = true

# Number of download threads to use when downloading rustup components.
# This should be set lower than crates, as rustup consists of large files.
download_threads = 4

# Where to download rustup files from.
source = "https://static.rust-lang.org"

# How many historical versions of Rust to keep.
# Setting these to 1 will keep only the latest version.
# Setting these to 2 or higher will keep the latest version, as well as historical versions.
# Setting these to 0 will stop Panamax from downloading the release entirely.
# Removing the line will keep all release versions.
keep_latest_betas = 0
keep_latest_nightlies = 0
keep_latest_stables = 1

# The platforms to include in the mirror
# These lists can be empty to mirror nothing, but if the setting is not set, it will default to all platforms.
# Note: These platforms should match the list on https://rust-lang.github.io/rustup/installation/other.html

# UNIX platforms
platforms_unix = [
  #   "aarch64-fuschia",
  # "aarch64-linux-android",
  "aarch64-pc-windows-msvc", #   "aarch64-unknown-hermit",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-none",
  "aarch64-unknown-none-softfloat", #   "aarch64-unknown-redox",
  #   "arm-linux-androideabi",
  "arm-unknown-linux-gnueabi",
  "arm-unknown-linux-gnueabihf",
  "arm-unknown-linux-musleabi",
  "arm-unknown-linux-musleabihf",
  "armebv7r-none-eabi",
  "armebv7r-none-eabihf",
  "armv5te-unknown-linux-gnueabi",
  "armv5te-unknown-linux-musleabi", #   "armv7-apple-ios",
  #   "armv7-linux-androideabi",
  "armv7-unknown-linux-gnueabi",
  "armv7-unknown-linux-gnueabihf", #   "armv7s-apple-ios",
  #   "asmjs-unknown-emscripten",
  #   "i386-apple-ios",
  #   "i586-pc-windows-msvc",
  #   "i586-unknown-linux-gnu",
  #   "i586-unknown-linux-musl",
  #   "i686-apple-darwin",
  #   "i686-linux-android",
  #   "i686-unknown-freebsd",
  "i686-unknown-linux-gnu",
  "i686-unknown-linux-musl", #   "mips-unknown-linux-gnu",
  #   "mips64-unknown-linux-gnuabi64",
  #   "mips64-unknown-linux-muslabi64",
  #   "mips64el-unknown-linux-gnuabi64",
  #   "mips64el-unknown-linux-muslabi64",
  #   "mipsel-unknown-linux-gnu",
  #   "mipsisa32r6el-unknown-linux-gnu",
  #   "mipsisa64r6-unknown-linux-gnuabi64",
  #   "mipsisa64r6el-unknown-linux-gnuabi64",
  # "nvptx64-nvidia-cuda",
  #   "powerpc-unknown-linux-gnu",
  #   "powerpc64-unknown-linux-gnu",
  #   "powerpc64le-unknown-linux-gnu",
  "riscv32gc-unknown-linux-gnu",
  "riscv32i-unknown-none-elf", #   "riscv32imac-unknown-none-elf",
  #   "riscv32imc-unknown-none-elf",
  #   "riscv64gc-unknown-none-elf",
  #   "riscv64imac-unknown-none-elf",
  #   "s390x-unknown-linux-gnu",
  "sparc64-unknown-linux-gnu", #   "sparcv9-sun-solaris",
  "thumbv6m-none-eabi",
  "thumbv7em-none-eabi",
  "thumbv7neon-linux-androideabi",
  "thumbv7neon-unknown-linux-gnueabihf",
  "wasm32-unknown-emscripten",
  "wasm32-unknown-unknown",
  "wasm32-wasi", #   "x86_64-apple-darwin",
  #   "x86_64-apple-ios",
  #   "x86_64-fortanix-unknown-sgx",
  #   "x86_64-fuschia",
  # "x86_64-linux-android",
  #   "x86_64-pc-solaris",
  #   "x86_64-rumprun-netbsd",
  #   "x86_64-sun-solaris",
  #   "x86_64-unknown-freebsd",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnux32",
  "x86_64-unknown-linux-musl", #   "x86_64-unknown-netbsd",
  #   "x86_64-unknown-redox",
]

# Windows platforms
platforms_windows = [
  #   "i586-pc-windows-msvc",
  "i686-pc-windows-gnu",
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-gnu",
  "x86_64-pc-windows-msvc",
]

[crates]
# These are the configuration parameters for the crates.io half of the mirror.
# This will download the crates.io-index, as well as the crates themselves.
# Once downloaded, it will then (optionally) rewrite the config.json to point to your mirror.

# Perform crates synchronization. Set this to false if you only want to mirror rustup.
sync = true

# Number of download threads to use when downloading crates components.
# This should be set higher than rustup, as crates consist of many small files.
download_threads = 16

# Where to download the crates from.
source = "https://crates.io/api/v1/crates"

# Where to clone the crates.io-index repository from.
source_index = "https://github.com/rust-lang/crates.io-index"

# URL where this mirror's crates directory can be accessed from.
# Used for rewriting crates.io-index's config.json.
# Remove this parameter to perform no rewriting.
base_url = "http://nexus3.matzov.idf/repository/crates.io"
